
import { useEffect, useRef, useState } from "react";
import "./newPrompt.css";
import Upload from "../upload/Upload";
import { IKImage } from "imagekitio-react";
import { createGeminiChat, callClaude, callGroq, callOpenRouter } from "../../lib/gemini";
import Markdown from "react-markdown";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useAuth } from "@clerk/clerk-react";

// ─── Fixed Answers ────────────────────────────────────────────────────────────
const fixedAnswers = {
  "what is cpu": "CPU stands for Central Processing Unit. It is known as the brain of the computer because it processes instructions and performs calculations.",
  "what is ram": "RAM stands for Random Access Memory. It is a temporary memory used to store data and programs currently being used by the computer.",
  "what is rom": "ROM stands for Read Only Memory. It is a permanent memory that stores important instructions needed to start a computer.",
  "what is motherboard": "The motherboard is the main circuit board of a computer that connects all hardware components together.",
  "what is hard disk": "A Hard Disk Drive (HDD) is a storage device used to store data and programs permanently.",
  "what is ssd": "SSD stands for Solid State Drive. It is a faster storage device than a hard disk because it uses flash memory.",
  "what is operating system": "An Operating System is system software that manages computer hardware and software resources. Examples are Windows, Linux, and macOS.",
  "what is software": "Software is a collection of programs and instructions that tell a computer what tasks to perform.",
  "what is hardware": "Hardware refers to the physical components of a computer that can be seen and touched.",
  "what is input device": "An input device is a hardware device used to enter data and instructions into a computer. Examples are keyboard and mouse.",
  "what is output device": "An output device is a hardware device that displays the results of computer processing. Examples are monitor and printer.",
  "what is keyboard": "A keyboard is an input device used to type data and commands into a computer.",
  "what is mouse": "A mouse is a pointing input device used to interact with graphical user interfaces.",
  "what is monitor": "A monitor is an output device that displays text, images, and videos generated by a computer.",
  "what is printer": "A printer is an output device that produces a hard copy of digital documents.",
  "what is scanner": "A scanner is an input device used to convert physical documents and images into digital form.",
  "what is usb": "USB stands for Universal Serial Bus. It is a standard used to connect devices and transfer data.",
  "what is cache memory": "Cache memory is a small high-speed memory that stores frequently used data to improve computer performance.",
  "what is computer virus": "A computer virus is a malicious program that can damage data, files, or the normal operation of a computer system.",
  "what is antivirus": "Antivirus software is a program designed to detect, prevent, and remove computer viruses and malware.",
  "what is cloud computing": "Cloud computing is the delivery of computing services such as storage and software over the internet.",
  "what is artificial intelligence": "Artificial Intelligence (AI) is a technology that enables machines to simulate human intelligence and decision-making.",
  "what is machine learning": "Machine Learning is a branch of AI that allows computers to learn from data and improve without explicit programming.",
  "what is binary number system": "The binary number system uses only two digits, 0 and 1, to represent data in computers.",
  "what is compiler": "A compiler is a software program that converts source code into machine code before execution.",
  "what is interpreter": "An interpreter is a software program that translates and executes source code line by line.",
  "what is algorithm": "An algorithm is a step-by-step procedure used to solve a problem or perform a task.",
  "what is flowchart": "A flowchart is a graphical representation of an algorithm using symbols and arrows.",
  "what is programming language": "A programming language is a formal language used to write instructions for computers.",
  "what is source code": "Source code is the human-readable set of instructions written by a programmer.",
  "what is machine code": "Machine code is the binary code that can be directly executed by a computer's processor.",
  "what is computer network": "The group of two or more computers and devices that are connected to share data, resources, and messages is called a Computer Network.",
  "what is telecommunications": "Telecommunications means sending and receiving information over a long distance with the help of an electronic device.",
  "what is broadband": "The high-speed internet connection that allows you to send and receive a large amount of data quickly is called Broadband.",
  "what is throughput": "The actual amount of data that is successfully sent or received over a network in a certain amount of time is called Throughput.",
  "what is bandwidth": "The maximum amount of data that a network can carry in a given time is called Bandwidth.",
  "what is data packet": "When we send information over a computer network, it is broken into small parts. Each part is called a Data Packet.",
  "what is frequency": "In telecommunications, frequency means how often data signals are sent over a communication channel in one second.",
  "what is data communication": "The transmission of data and information between a computer and another electronic device is called Data Communication.",
  "what is communication media": "The physical channels used to send data and information between devices in a network are called Communication Media.",
  "what are the types of communication media": "They are Guided Media and Unguided Media.",
  "write any three features of cat6 cables": "1) They support speeds of up to 10 Gbps over 100 meters. 2) They can reach 10 Gbps over short distances. 3) They have better insulation and tightly twisted wire pairs.",
  "what is wifi": "The wireless technology that allows devices to connect to the internet without using cables is called Wi-Fi.",
  "what is rfid": "RFID (Radio Frequency Identification) is a wireless technology that uses radio waves to identify and track tags attached to objects.",
  "what is connector": "A small hardware device used to connect a communication media to a network device is called a connector. Example: RJ45 connector.",
  "what is media converter": "A device in a computer network that connects different types of cables, such as copper and fiber optic cable, is called a media converter.",
  "what is repeater": "A network device that accepts a weak signal, regenerates it, and forwards it along the network is called a repeater.",
  "what is hub": "A network device with multiple ports used to connect different computers on a network is called a hub.",
  "what is switch": "A network device that joins multiple computers together to share information among them is called a switch.",
  "what is bridge": "A network device that interconnects two networks that use a similar protocol is called a bridge.",
  "what is router": "A network device that joins multiple wired or wireless networks together is called a router.",
  "what is gateway": "A network device that connects two different networks and allows them to communicate with each other is called a gateway.",
  "what is topology": "The interconnected layout or pattern of computers in a network is called topology. Types: Bus, Star, Ring, and Hybrid topology.",
  "what are the types of computer networks": "The types of computer networks are PAN (Personal Area Network), LAN (Local Area Network), MAN (Metropolitan Area Network), and WAN (Wide Area Network).",
  "what are the types of computer network architecture": "Client-Server network and Peer-to-Peer network.",
  "what is protocol": "A set of rules followed for interconnection and communication between computers in a network is called a protocol. Examples: TCP/IP, HTTP, HTTPS, FTP.",
  "what is internet": "A global network of computers and devices that allows people to share information and communicate across long distances is called the Internet.",
  "what is intranet": "A private network accessible only to an organization's staff is called an Intranet.",
  "what is extranet": "A controlled private network that allows access to outsiders such as partners and clients is called an Extranet.",
  "what is data": "A collection of raw facts or figures that may not have meaning on their own is called data.",
  "what is information": "The useful result obtained after arranging or processing data is called information.",
  "what is database": "A systematic way to store and manage data is called a database.",
  "what are recent trends and technology in dbms": "Cloud-based databases, NoSQL databases, in-memory databases, and distributed databases.",
  "what are the features of database": "Data storage, data retrieval, data manipulation, data integration, security, data backup, and recovery.",
  "write any four benefits of dbms": "1) Easy data storage and retrieval. 2) Reduced data redundancy. 3) Allows multiple user access. 4) Supports data backup and recovery.",
  "write any four challenges of dbms": "1) Requires technical knowledge to manage. 2) Initial setup cost can be high. 3) Data security risks if not managed properly. 4) Performance may be slow with very large data.",
  "what is rdbms": "A type of DBMS that stores data in tables made of rows and columns is called RDBMS.",
  "what are data types": "The kind of data that can be stored in each column of a database table is called a data type. Types: numeric, character, date/time, and boolean.",
  "what is table": "A structured way to store data in rows and columns in a database is called a table.",
  "what is field": "A column in a table that contains a single type of data under a specific category is called a field.",
  "what is record": "A row of data that represents one complete set of information about a single entity in a database table is called a record.",
  "what is primary key": "A field that uniquely identifies each record in a table is called a primary key. Features: uniquely identifies a record, cannot be null, only one per table, no duplicate values.",
  "what is foreign key": "A field in one table that refers to the primary key of another table is called a foreign key. Features: creates relationships between tables, ensures data integrity.",
  "what is composite key": "A key made by combining two or more fields to uniquely identify a record is called a composite key.",
  "what is mysql": "An open-source relational database management system that uses SQL to store, manage, and organize data is called MySQL. Features: simple language, supports relational data, strong security, widely used.",
  "what is multimedia": "The term multimedia comes from two words — multi (many) and media (means of communication). Multimedia includes text, graphics, audio, video, and animation.",
  "what is bytebot": "ByteBot is an AI-powered chat assistant built with React, Node.js, MongoDB, and Google Gemini.",
  "who made you": "I was built by Denish using the ByteBot AI chat app.",
  "write a python program to find the area of a rectangle": "l = float(input('Length: '))\nb = float(input('Breadth: '))\narea = l * b\nprint('Area =', area)",
  "write a python program to find the area of a circle": "import math\nr = float(input('Radius: '))\narea = math.pi * r * r\nprint('Area =', area)",
  "write a python program to add two numbers": "a = int(input('Enter a: '))\nb = int(input('Enter b: '))\nprint('Sum =', a + b)",
  "write a python program to check even or odd": "n = int(input('Enter number: '))\nif n % 2 == 0:\n    print('Even')\nelse:\n    print('Odd')",
  "write a python program to find factorial": "n = int(input('Enter number: '))\nf = 1\nfor i in range(1, n+1):\n    f *= i\nprint('Factorial =', f)",
  "write a python program to print fibonacci series": "a, b = 0, 1\nfor i in range(10):\n    print(a, end=' ')\n    a, b = b, a + b",
  "write a python program to reverse a string": "s = input('Enter string: ')\nprint(s[::-1])",
  "write a python program to check palindrome": "s = input('Enter string: ')\nif s == s[::-1]:\n    print('Palindrome')\nelse:\n    print('Not palindrome')",
  "write a python program to find simple interest": "p = float(input('Principal: '))\nr = float(input('Rate: '))\nt = float(input('Time: '))\nsi = (p * r * t) / 100\nprint('Simple Interest =', si)",
  "write a python program to print multiplication table": "n = int(input('Number: '))\nfor i in range(1, 11):\n    print(n, 'x', i, '=', n*i)",
  "write a python program to find the square root of a number": "import math\nn = float(input('Number: '))\nprint('Square root =', math.sqrt(n))",
  "what keyword is used to define a function in python": "def",
  "what symbol is used for comments in python": "# (hash symbol)",
  "what is a list in python": "A list is an ordered, mutable collection of items. Example: [1, 2, 3]",
  "create a basic html page": "<!DOCTYPE html>\n<html>\n<head>\n  <title>My Page</title>\n</head>\n<body>\n  <h1>Hello World</h1>\n</body>\n</html>",
  "write html code to create a hyperlink": "<a href='https://www.google.com'>Visit Google</a>",
  "write html code to display an image": "<img src='image.jpg' alt='My Image' width='300'>",
  "what is photosynthesis": "Photosynthesis is the process by which green plants make food using sunlight, water, and CO2. Formula: 6CO2 + 6H2O → C6H12O6 + 6O2.",
  "what is newton first law": "Newton's First Law: An object at rest stays at rest and an object in motion stays in motion unless acted upon by an external force.",
  "what is newton second law": "Newton's Second Law: Force = Mass × Acceleration (F = ma).",
  "what is newton third law": "Newton's Third Law: For every action there is an equal and opposite reaction.",
  "what is osmosis": "Osmosis is the movement of water from high concentration to low concentration through a semi-permeable membrane.",
  "what is dna": "DNA stands for Deoxyribonucleic Acid. It carries genetic information in living organisms.",
  "what is ohm law": "Ohm's Law: V = IR (Voltage = Current × Resistance).",
  "what is the speed of light": "The speed of light is 3 × 10⁸ meters per second.",
  "what is gravity": "Gravity is the force of attraction between two masses. On Earth, g = 9.8 m/s².",
  "what is nibandha": "निबन्ध एउटा विषयमा आफ्नो विचार र तर्क व्यक्त गरिएको गद्य रचना हो। यसमा भूमिका, विषय विस्तार र उपसंहार हुन्छ।",
  "what is nepal ko rastriya phool": "नेपालको राष्ट्रिय फूल लालीगुराँस (Rhododendron) हो।",
  "what is nepal ko rastriya janawar": "नेपालको राष्ट्रिय जनावर गाई हो।",
  "what is nepal ko rastriya pakshi": "नेपालको राष्ट्रिय पक्षी डाँफे (Himalayan Monal) हो।",
  "what is sandhi": "सन्धि भनेको दुई शब्द वा वर्णहरू मिल्दा हुने परिवर्तन हो। प्रकार: स्वर सन्धि, व्यञ्जन सन्धि र विसर्ग सन्धि।",
  "what is sangya": "संज्ञा भनेको कुनै व्यक्ति, वस्तु, स्थान वा भावको नाम जनाउने शब्द हो।",
  "what is sarwanam": "सर्वनाम भनेको संज्ञाको ठाउँमा प्रयोग हुने शब्द हो। जस्तै: म, तिमी, ऊ, हामी।",
};

// ─── Quiz Bank (50 questions) ─────────────────────────────────────────────────
const quizBank = [
  { question: "What branch of AI helps computers understand human language?", answer: "NLP (Natural Language Processing)" },
  { question: "Which protocol secures websites?", answer: "HTTPS" },
  { question: "Which language structures web pages?", answer: "HTML" },
  { question: "Which language styles web pages?", answer: "CSS" },
  { question: "Which language adds interactivity to websites?", answer: "JavaScript" },
  { question: "What does DOM stand for?", answer: "Document Object Model" },
  { question: "Which company created ChatGPT?", answer: "OpenAI" },
  { question: "Which company created Gemini AI?", answer: "Google" },
  { question: "Which database is used in the MERN stack?", answer: "MongoDB" },
  { question: "Which library is used for React routing?", answer: "React Router" },
  { question: "Which protocol transfers files?", answer: "FTP" },
  { question: "Which protocol sends emails?", answer: "SMTP" },
  { question: "Which protocol receives emails?", answer: "POP3" },
  { question: "What does API stand for?", answer: "Application Programming Interface" },
  { question: "What JavaScript keyword declares a constant?", answer: "const" },
  { question: "What JavaScript keyword declares a variable?", answer: "let" },
  { question: "What React hook stores component data?", answer: "useState" },
  { question: "What React hook handles side effects?", answer: "useEffect" },
  { question: "Which HTML tag creates a hyperlink?", answer: "<a> tag" },
  { question: "Which HTML tag displays an image?", answer: "<img> tag" },
  { question: "Which CSS property changes text color?", answer: "color" },
  { question: "Which CSS property changes font size?", answer: "font-size" },
  { question: "Which CSS layout uses rows and columns (2D)?", answer: "CSS Grid" },
  { question: "Which CSS layout system is one-dimensional?", answer: "Flexbox" },
  { question: "What does SQL stand for?", answer: "Structured Query Language" },
  { question: "What does CPU stand for?", answer: "Central Processing Unit" },
  { question: "What does RAM stand for?", answer: "Random Access Memory" },
  { question: "What does ROM stand for?", answer: "Read Only Memory" },
  { question: "What does URL stand for?", answer: "Uniform Resource Locator" },
  { question: "What does GUI stand for?", answer: "Graphical User Interface" },
  { question: "What does OOP stand for?", answer: "Object-Oriented Programming" },
  { question: "What are the four pillars of OOP?", answer: "Encapsulation, Inheritance, Polymorphism, Abstraction" },
  { question: "What is a primary key in a database?", answer: "A field that uniquely identifies each record in a table" },
  { question: "What is a foreign key?", answer: "A field that refers to the primary key of another table" },
  { question: "What does LAN stand for?", answer: "Local Area Network" },
  { question: "What does WAN stand for?", answer: "Wide Area Network" },
  { question: "What is binary number system?", answer: "A number system using only 0 and 1" },
  { question: "What is the chemical formula of water?", answer: "H2O" },
  { question: "What is the chemical formula of carbon dioxide?", answer: "CO2" },
  { question: "What is Newton's Second Law?", answer: "F = ma (Force = Mass × Acceleration)" },
  { question: "What is the SI unit of force?", answer: "Newton (N)" },
  { question: "What is the SI unit of power?", answer: "Watt (W)" },
  { question: "What is the powerhouse of the cell?", answer: "Mitochondria" },
  { question: "What is the basic unit of life?", answer: "Cell" },
  { question: "What is the speed of light?", answer: "3 × 10⁸ m/s" },
  { question: "What is Nepal's national flower?", answer: "Rhododendron (लालीगुराँस)" },
  { question: "What is Nepal's national bird?", answer: "Himalayan Monal (डाँफे)" },
  { question: "What is Nepal's national animal?", answer: "Cow (गाई)" },
  { question: "When did Prithvi Narayan Shah unify Nepal?", answer: "1768 AD" },
  { question: "What is the capital of Nepal?", answer: "Kathmandu (काठमाडौं)" },
];

function getRandomQuestions(n = 25) {
  const shuffled = [...quizBank].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(n, shuffled.length));
}

let quizSession = null;

function handleQuizGame(text, speakFn) {
  const msg = text.trim().toLowerCase();

  if (
    msg.includes("create a game") ||
    msg.includes("start quiz") ||
    msg.includes("create quiz") ||
    msg.includes("quiz game")
  ) {
    const selected = getRandomQuestions(25);
    quizSession = { active: true, questions: selected, score: 0 };
    setTimeout(() => {
      speakFn("Get ready for the quiz! Here are the rules. I will show you 25 randomly selected questions. Try to answer each one yourself. When you want to know the answer, just say answer of question 1, or any number. For every correct answer you get one chocolate point. Good luck! Let us begin!");
    }, 500);
    let result = "🎮 **Quiz Game Started!**\n\n";
    result += "📋 **Rules:**\n";
    result += "- 25 randomly selected questions\n";
    result += "- Try to answer yourself first\n";
    result += "- Type **answer of question 3** to reveal any answer\n";
    result += "- 🍫 **1 chocolate point** for every correct answer!\n\n---\n\n";
    selected.forEach((item, i) => { result += `**${i + 1}.** ${item.question}\n\n`; });
    result += "---\n*Type: **answer of question 1** (1–25)*";
    return result;
  }

  if (
    msg.includes("give me a question") ||
    msg.includes("ask me a question") ||
    msg.includes("random question") ||
    msg === "question"
  ) {
    const q = quizBank[Math.floor(Math.random() * quizBank.length)];
    quizSession = { active: true, questions: [q], score: 0, singleMode: true };
    return `🤔 **Question:**\n\n${q.question}\n\n*Type **show answer** when you're ready!*`;
  }

  if ((msg === "show answer" || msg === "answer") && quizSession?.singleMode) {
    const q = quizSession.questions[0];
    return `✅ **Answer:** ${q.answer}\n\n*Type **give me a question** for another one!*`;
  }

  const answerMatch = msg.match(/answer(?:\s+of)?(?:\s+question)?\s+(\d+)/);
  if (answerMatch) {
    const num = parseInt(answerMatch[1]);
    if (!quizSession || quizSession.singleMode) return '⚠️ No quiz is active. Type **"create a game"** to start one!';
    if (num < 1 || num > quizSession.questions.length) return `⚠️ Please enter a number between 1 and ${quizSession.questions.length}.`;
    const q = quizSession.questions[num - 1];
    return `✅ **Answer to Question ${num}:**\n\n**Q:** ${q.question}\n**A:** ${q.answer}\n\n🍫 *+1 chocolate point if you got it right!*`;
  }

  return null;
}

// ─── SVG Icons ────────────────────────────────────────────────────────────────

const IconCopy = ({ copied }) => copied ? (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#4ade80" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
    <polyline points="20 6 9 17 4 12" />
  </svg>
) : (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
  </svg>
);

const IconSpeak = ({ active }) => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke={active ? "#4ade80" : "currentColor"} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5" />
    <path d="M19.07 4.93a10 10 0 0 1 0 14.14" />
    <path d="M15.54 8.46a5 5 0 0 1 0 7.07" />
  </svg>
);

const IconLike = ({ active }) => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill={active ? "#4ade80" : "none"} stroke={active ? "#4ade80" : "currentColor"} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3H14z" />
    <path d="M7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3" />
  </svg>
);

const IconDislike = ({ active }) => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill={active ? "#e55571" : "none"} stroke={active ? "#e55571" : "currentColor"} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M10 15v4a3 3 0 0 0 3 3l4-9V2H5.72a2 2 0 0 0-2 1.7l-1.38 9a2 2 0 0 0 2 2.3H10z" />
    <path d="M17 2h2.67A2.31 2.31 0 0 1 22 4v7a2.31 2.31 0 0 1-2.33 2H17" />
  </svg>
);

const IconReload = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <polyline points="23 4 23 10 17 10" />
    <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10" />
  </svg>
);

const IconMic = ({ active }) => (
  <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke={active ? "#e55571" : "currentColor"} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z" />
    <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
    <line x1="12" y1="19" x2="12" y2="23" />
    <line x1="8" y1="23" x2="16" y2="23" />
  </svg>
);

const IconSend = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
    <line x1="12" y1="19" x2="12" y2="5" />
    <polyline points="5 12 12 5 19 12" />
  </svg>
);

// ─── Message Actions ──────────────────────────────────────────────────────────

const MessageActions = ({ answer, feedback, setFeedback, onRegenerate, onSpeakManual }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(answer);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <div className="messageActions">
      <button type="button" onClick={handleCopy} title={copied ? "Copied!" : "Copy"}>
        <IconCopy copied={copied} />
      </button>
      <button type="button" onClick={() => onSpeakManual(answer)} title="Read aloud">
        <IconSpeak />
      </button>
      <button type="button" onClick={() => setFeedback(feedback === "like" ? null : "like")} title="Like">
        <IconLike active={feedback === "like"} />
      </button>
      <button type="button" onClick={() => setFeedback(feedback === "dislike" ? null : "dislike")} title="Dislike">
        <IconDislike active={feedback === "dislike"} />
      </button>
      <button type="button" onClick={onRegenerate} title="Regenerate">
        <IconReload />
      </button>
    </div>
  );
};

// ─── Main Component ───────────────────────────────────────────────────────────

const NewPrompt = ({ data }) => {
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [isListening, setIsListening] = useState(false);
  const [speakEnabled, setSpeakEnabled] = useState(false);
  const [feedback, setFeedback] = useState(null);
  const [aiSource, setAiSource] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [img, setImg] = useState({
    isLoading: false,
    error: "",
    dbData: {},
    aiData: {},
  });

  const { getToken } = useAuth();

  const chat = createGeminiChat(data?.history);

  const endRef = useRef(null);
  const formRef = useRef(null);
  const inputRef = useRef(null);
  const recognitionRef = useRef(null);
  const lastQuestionRef = useRef("");

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [data, question, answer, img.dbData]);

  useEffect(() => {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SpeechRecognition) return;
    const recognition = new SpeechRecognition();
    recognition.continuous = false;
    recognition.interimResults = false;
    recognition.lang = "en-US";
    recognition.onresult = (event) => {
      const transcript = event.results[0][0].transcript;
      if (inputRef.current) inputRef.current.value = transcript;
    };
    recognition.onend = () => setIsListening(false);
    recognition.onerror = () => setIsListening(false);
    recognitionRef.current = recognition;
  }, []);

  const toggleListening = () => {
    if (!recognitionRef.current) {
      alert("Voice input is not supported in this browser. Try Chrome.");
      return;
    }
    if (isListening) {
      recognitionRef.current.stop();
      setIsListening(false);
    } else {
      recognitionRef.current.start();
      setIsListening(true);
    }
  };

  const stripMarkdown = (text) =>
    text.replace(/\*\*/g, "").replace(/\*/g, "").replace(/#/g, "").replace(/\|/g, "");

  const speak = (text) => {
    if (!speakEnabled) return;
    if (!window.speechSynthesis) return;
    window.speechSynthesis.cancel();
    const utterance = new SpeechSynthesisUtterance(stripMarkdown(text));
    utterance.lang = "en-US";
    window.speechSynthesis.speak(utterance);
  };

  const speakManual = (text) => {
    if (!window.speechSynthesis) return;
    window.speechSynthesis.cancel();
    const utterance = new SpeechSynthesisUtterance(stripMarkdown(text));
    utterance.lang = "en-US";
    window.speechSynthesis.speak(utterance);
  };

  const queryClient = useQueryClient();

  const mutation = useMutation({
    mutationFn: async () => {
      const token = await getToken();
      return fetch(`${import.meta.env.VITE_API_URL}/api/chats/${data._id}`, {
        method: "PUT",
        credentials: "include",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          question: question.length ? question : undefined,
          answer,
          img: img.dbData?.filePath || undefined,
        }),
      }).then((res) => res.json());
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["chat", data._id] }).then(() => {
        formRef.current?.reset();
        setQuestion("");
        setAnswer("");
        setFeedback(null);
        setAiSource(null);
        setIsLoading(false);
        setImg({ isLoading: false, error: "", dbData: {}, aiData: {} });
      });
    },
    onError: (err) => console.log(err),
  });

  const buildMessages = (text) => {
    const msgs = data?.history?.map(({ role, parts }) => ({
      role: role === "model" ? "assistant" : "user",
      content: parts[0].text,
    })) || [];
    msgs.push({ role: "user", content: text });
    return msgs;
  };

  const add = async (text, isInitial) => {
    if (!isInitial) setQuestion(text);
    lastQuestionRef.current = text;
    setFeedback(null);
    setAiSource(null);
    setAnswer("");        // ← clear old answer immediately
    setIsLoading(true);  // ← show loading dots

    // 1️⃣ Quiz game
    const quizResult = handleQuizGame(text, speak);
    if (quizResult !== null) {
      setAnswer(quizResult);
      speak(quizResult);
      setIsLoading(false);
      setTimeout(() => mutation.mutate(), 3000);
      return;
    }

    // 2️⃣ Fixed answers
    const normalizedText = text.trim().toLowerCase();
    if (fixedAnswers[normalizedText]) {
      const fixedAnswer = fixedAnswers[normalizedText];
      setAnswer(fixedAnswer);
      speak(fixedAnswer);
      setIsLoading(false);
      setTimeout(() => mutation.mutate(), 3000);
      return;
    }

    // Track *why* each provider actually failed, so the final message (if we
    // get there) tells the truth instead of guessing "rate limit" for all 4.
    const failures = [];

    // 3️⃣ Try Gemini
    try {
      const message = Object.entries(img.aiData).length ? [img.aiData, text] : text;
      const stream = await chat.sendMessageStream({ message });
      let accumulatedText = "";
      for await (const chunk of stream) {
        accumulatedText += chunk.text;
        setAnswer(accumulatedText);
      }
      speak(accumulatedText);
      setAiSource("gemini");
      setIsLoading(false);
      mutation.mutate();
      return;
    } catch (err) {
      console.warn("Gemini failed:", err);
      failures.push({ label: "🔵 Gemini", reason: err?.message || "Unknown error" });
    }

    // 4️⃣ Try Claude
    try {
      const { text: claudeText, source } = await callClaude(buildMessages(text));
      setAnswer(claudeText);
      speak(claudeText);
      setAiSource(source);
      setIsLoading(false);
      mutation.mutate();
      return;
    } catch (err) {
      console.warn("Claude failed:", err);
      failures.push({ label: "🟣 Claude", reason: err?.message || "Unknown error" });
    }

    // 5️⃣ Try Groq
    try {
      const { text: groqText, source } = await callGroq(buildMessages(text));
      setAnswer(groqText);
      speak(groqText);
      setAiSource(source);
      setIsLoading(false);
      mutation.mutate();
      return;
    } catch (err) {
      console.warn("Groq failed:", err);
      failures.push({ label: "🟠 Groq", reason: err?.message || "Unknown error" });
    }

    // 6️⃣ Try OpenRouter
    try {
      const { text: orText, source } = await callOpenRouter(buildMessages(text));
      setAnswer(orText);
      speak(orText);
      setAiSource(source);
      setIsLoading(false);
      mutation.mutate();
      return;
    } catch (err) {
      console.warn("OpenRouter failed:", err);
      failures.push({ label: "🟡 OpenRouter", reason: err?.message || "Unknown error" });
    }

    // 7️⃣ All failed — show the real reason for each one instead of a
    // hardcoded guess, so a bad key or a renamed model is obvious at a glance.
    setAnswer(
      "⚠️ **All AI services are currently unavailable.**\n\n" +
      failures.map((f) => `- ${f.label}: ${f.reason}`).join("\n") +
      "\n\nPlease wait a few minutes and try again, or check your API keys in the `.env` file."
    );
    setIsLoading(false);
  };

  const handleRegenerate = () => {
    if (!lastQuestionRef.current) return;
    window.speechSynthesis?.cancel();
    setAnswer("");
    add(lastQuestionRef.current, true);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const text = e.target.text.value;
    if (!text) return;
    add(text, false);
  };

  const hasRun = useRef(false);
  useEffect(() => {
    if (!hasRun.current) {
      if (data?.history?.length === 1) {
        add(data.history[0].parts[0].text, true);
      }
    }
    hasRun.current = true;
  }, []);

  return (
    <>
      {img.isLoading && <div>Loading...</div>}
      {img.dbData?.filePath && (
        <IKImage
          urlEndpoint={import.meta.env.VITE_IMAGE_KIT_ENDPOINT}
          path={img.dbData?.filePath}
          width="380"
          transformation={[{ width: 380 }]}
        />
      )}

      {/* User question bubble */}
      {question && (
        <div className="message user">
          <span className="senderLabel">You</span>
          {question}
        </div>
      )}

      {/* Loading dots — visible while all APIs are being tried */}
      {isLoading && (
        <div className="message">
          <span className="senderLabel">ByteBot</span>
          <span className="typingDots">
            <span>.</span><span>.</span><span>.</span>
          </span>
        </div>
      )}

      {/* Answer — only shows when loading is done */}
      {!isLoading && answer && (
        <div className="message">
          <span className="senderLabel">ByteBot</span>
          <Markdown>{answer}</Markdown>
          {aiSource && (
            <div style={{ fontSize: "11px", opacity: 0.4, marginTop: "4px", fontStyle: "italic" }}>
              {aiSource === "claude"
                ? "⚡ Answered by Claude"
                : aiSource === "groq"
                ? "🦙 Answered by Groq"
                : aiSource === "openrouter"
                ? "🌐 Answered by OpenRouter"
                : "✨ Answered by Gemini"}
            </div>
          )}
          {/* Always visible — never hides */}
          <MessageActions
            answer={answer}
            feedback={feedback}
            setFeedback={setFeedback}
            onRegenerate={handleRegenerate}
            onSpeakManual={speakManual}
          />
        </div>
      )}

      <div className="endChat" ref={endRef}></div>

      <form className="newForm" onSubmit={handleSubmit} ref={formRef}>
        <Upload setImg={setImg} />
        <input id="file" type="file" multiple={false} hidden />
        <input
          type="text"
          name="text"
          placeholder="Ask anything... or type 'create a game'"
          ref={inputRef}
        />
        <button
          type="button"
          onClick={() => {
            if (speakEnabled) window.speechSynthesis?.cancel();
            setSpeakEnabled(!speakEnabled);
          }}
          title={speakEnabled ? "Auto-speak ON — click to turn off" : "Auto-speak OFF — click to turn on"}
          style={{ opacity: speakEnabled ? 1 : 0.35 }}
        >
          <IconSpeak active={speakEnabled} />
        </button>
        <button
          type="button"
          onClick={toggleListening}
          className={`iconBtn micBtn${isListening ? " listening" : ""}`}
          title={isListening ? "Listening..." : "Speak your question"}
        >
          <IconMic active={isListening} />
        </button>
        <button type="submit" className="sendBtn">
          <IconSend />
        </button>
      </form>
    </>
  );
};

export default NewPrompt;
